### ISSUE TITLE
Vignette: add the two png images in vignette/images to the Rmd and describe output

### ISSUE THREAD

**Issue by ByrumLab** [ByrumLab/proteoDA#200]

**Comment by tjthurman** [comment]
I got started on this with PR #210, but we also need to make sure the code in the vignette(s) is running, not just displayed. R code blocks should be specified with {r} after the three backticks to define a code block: this ensures the knitr actually runs the code. Some of the code we don't actually want to run, e.g., any of the `write_*` functions, as we don't want a bunch of random files getting written and save at package/vignette build time. Those code blocks should be specified as {r, eval = F}.
