### ISSUE TITLE
limma plots column order

### ISSUE THREAD

**Issue by GolAGitHub** [ByrumLab/proteoDA#255]
Hi,

I am wondering if there is a way to specify the order of the groups shown in the abundance plots when using the write_limma_plots?

Great package otherwise!

Thak you.

**Comment by tjthurman** [comment]
Is this for the abundance plots on the right hand side of the output HTML report? At the moment, I don't think we have a documented way to do that directly. If you haven't already tried this, you could try changing the order of the sample metadata at the very first step, when you make the initial DAList. I believe the order of the samples in the abundance plots is just taken from that (but haven't been able to double-check). Make sure you re-order the columns of the input data as needed. Let me know if that works!

**Comment by tjthurman** [comment]
Great, glad that did it!
